added repositories
n1EzeR/kaspi_parser pull request #4
Opened 2020-03-28 07:12 UTC by daryn2

2020-03-28 07:33 UTC, zhanymkanov requested changes
Переименуй еще файлы в просто category/reviews/details без repository, они и так находятся в папке репозиторис. В спайдерс было добавлено спайдерс чтобы визуально отделить их от других файлов

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +                print('Categories was created successfully')
Используй LOGGER.info(), не print

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +            "title" : '',
не смешивай "" и ''
используй лучше ''

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +    def get_values(self, details):
что такое values? назови по конкретней

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +        dict = {
не используй назавние dict, оно во-первых оверрайдит функцию dict, во вторых не объясняет содержимое дикта

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +        if ("title" in details):
здесь лучше заменить на dict['title'] = details.get('title', '') сразу без проверки, так как эти все колонки нам нужны, нельзя их пропускать. Они либо есть либо заполнены NULL

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +        if ("parsed_details" in details):
здесь убери скобки с if'a и все остальное замени на dict[X] = details.get(X, '')

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +    def insert_details(self):
между функциями 2 blank line'a перед пушом просто нажимай cmd + alt + L

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +
внутри функции до 2-ух blank line'ов

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +                            ''',  [dict['title'], dict['url'], dict['brand'], dict['rating'],
как нибудь визуально отдели параметры от выполняемой строки

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +
в конце программы всегда только 1 blank line, не больше не меньше

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +from spiders.utils import _get_latest_date_in_dir
зажми cmd+alt+shift+l и выбери optimize imports, у импортов также есть свой порядок

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/category_repository.py
> +        # self.init_categories()
удали если не используется

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/category_repository.py
> +        self.con = ps.connect(dbname= config('DB_NAME'), user=config("DB_USERNAME"),
здесь тоже либо одинарные либо двойные ковычки (лучш одинарные)

2020-03-28 07:33 UTC, zhanymkanov commented on code/repositories/category_repository.py
> +            print('Could not create categories table: ', e)
лучше LOGGER.warning(f'Could not create categories table: {e}')

2020-03-28 07:34 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +                print('Categories was created successfully')
или warning если ексепшн

2020-03-28 10:36 UTC, daryn2 commented on code/repositories/details_repository.py
> +        if ("title" in details):
то есть заменить с
if ("url" in details):
    db_data['url'] = details['url']
на
db_data['url'] = details.get('url','')

2020-03-28 16:12 UTC, zhanymkanov commented on code/repositories/details_repository.py
> +        if ("title" in details):
да. только не дб дата назови как нибудь по другому. например product. дб_дата все также абстрактно и непонятно что за дата.

2020-03-30 13:27 UTC, zhanymkanov requested changes

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +    logging.basicConfig(filename= 'db.log', level=logging.DEBUG)
сделай логгер как в utils

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +from idna import unicode
cmd + alt + shift + l, отметь очистку импорта

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                              password=config("DB_PASS"), host=config('DB_HOST'))
замени на одинарные ковычки

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                )''')
если получится, сделай ковычки симметричными

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +            logging.error('Could not create products table: ', e)
между методами 1 пустая строка, между функциями 2

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +        except ps.Error as e:
давай лучше exc, a не e

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +            logging.error('Could not create products table: ', e)
лучше f-string, через logging.error(f'Could not create products table: {exc}')

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +        postgreSQL_select_Query = "select id from CATEGORIES where name = %s"
здесь можно просто query, так как видно что она делает

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                if (category_id == None): return category_id
на None лучше проверять через is, if category_id is None.
one-liner лучше убратьи перенсти на новую строку - не pythonic

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +        x = os.chdir('../data/products/')
лучше не менять директорию в процессе работы, лучше просто путь к файлу

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                    print(file_name)
лучше более детальный логгер

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                if (file_name == 'computers-list.json' or file_name == 'smartphones-list.json'):
лучше создать сет allowed_categories и проверять if file_name in allowed_categories.
сохраняется open-closed principle из solid

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +        print(data)
добавить более детальный логгер

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                        url_of_product = products['shopLink']
product_url, product_name

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                        f.close()
точно нужно закрывать f после первой итерации продукта? лучше вообще убрать f.close()
когда ты открываешь файл через with open() он сам его закрывает после окончания работы.

2020-03-30 13:27 UTC, zhanymkanov commented on code/repositories/products.py
> +                                logging.error('Could not insert data in categories table')
не забудь передать этот ексепшн в логгер. (логгер переделать как в utils)

2020-04-06 08:03 UTC, zhanymkanov requested changes
Если код повторяется, посмотри в сторону наследования. Можно ли как-то все это абстрагировать и не повторять код. Если код можно абстрагировать, то можно использовать те абстрактные названия которые ты писал вроде insert_data, чтобы например заменить методы insert_products, insert_details, insert_categories.

2020-04-06 08:03 UTC, zhanymkanov commented on code/products.py
> +
убери строку, должно быть 2 между функциями или после импорта

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/category.py
> +    logging.basicConfig(filename= 'db.log', level=logging.DEBUG)
здесь логгер как в utils сделать. Заметь, что LOGGER нужно вынести из класса в модуль (сразу после импорта и перед классом, не в нем)

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/category.py
> +
между методами 1 строка

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/category.py
> +        x = os.chdir('../data/products/')
не x, а products_dir

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/category.py
> +                dict = json.loads(f.readlines()[1][:-2])
объясни в комменте в коде почему [1][:-2], что там за структура находится

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/category.py
> +                f.close()
f.close() не нужен - with self.con сам его закреот

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                print('Categories was created successfully')
используй логгер как в utils

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +        details_db_data = {
лучше просто инициализировать пустой дикт (details = {})
метод на самом деле парсит данные, переименовать лучше в parse_details
details_db_data можно переименовать в details, db_data это лишнее плюс не дает конкретики что за дата - импорт/экспорт даты?

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +        data = os.listdir(x)
можно заменить на os.listdir('../data/details/')
дай data нормальное название.
мы же по ней итерируемся. назови что мы итерируем. 
в папке детейлс лежат продукты, так ведь? мы ведь итерируемся по продуктам?

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +        for file_name in data:
Непонятно что такое file_name

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                details_data = ast.literal_eval(f.read())
без ast никак?
используй json, придерживайся тех же библиотек что и во всем коде.

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                for details in details_data:
details_data асбтрактно и непонятно.
если это итерируемый объект, то назови через что мы итерируемся

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                        db_data = self.get_db_data(details)
db_data - абстрактно и непонятно

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                            cur.execute('''
запрос сделай симметричным

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                            print('Could not insert data in categories table')
заменить на логгер

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/details.py
> +                    f.close()
with open автоматически закроет файл, f.close() не нужен. IDE не жалуется?

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +    LOGGER = logging.getLogger()
вынеси логгер из класса, он должен быть доступен всему модулю. пересмотри как он сделал в utils. Не забудь про пустые строки до и после.

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +    allowed_categories = {'computers-list.json', 'smartphones-list.json'}
allowed_categories используется только в том методе на проверку, так и храни его там

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                if (detail_id is None): return detail_id
по pep8 не рекомендуется делать one line'ры разных действий.
проверка на условие - одно действие
return - другое.
и убери скобки.
Если IDE подчеркивает что-то желтым, посмотри на что он жалуется - может на скобки, может на пустые строки

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                if (category_id is None): return category_id
здесь тоже

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +            self.LOGGER.warning(f'Could not get category by name: { exc }')
пробелы межды { } и exc по PEP не нужны

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +        # x = os.chdir('../data/products/')
удали если не используется

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                    for products in products_data:
множественное число если это лист или любой другой итерируемый объект. переименуй products > product, products_data > products_data

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +            data = os.listdir('../data/products/' + last_date)
лучше все таки f'../data/products/{last_date}' - это и быстрее (не конкатенирует эти строки) и выглядит лучше

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +        print(last_date)
зачем здесь принт? если дебаг - удали, если инфа нужна - делай логгер и объясни что показывается

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                if (file_name in self.allowed_categories):
скобки, плюс перенеси сюда allowed_categories

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                        print(details_id)
зачем здесь принт?

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +        query = "select id from DETAILS where url = %s"
Если IDE не распознает что это SQL, то нужно выводить капсом ключевые слова SELECT, FROM, DETAILS, WHERE, а все остальное маленьким

2020-04-06 08:03 UTC, zhanymkanov commented on code/repositories/products.py
> +                self.LOGGER.info("Products was created successfully")
were*

2020-04-07 07:02 UTC, zhanymkanov commented
Слушай, а почему мы вообще назвали их repository? Весь код же это коннект к БД, парс и инициализация данных?

2020-04-07 07:10 UTC, zhanymkanov commented on code/repositories/details.py
> +                    url                 varchar(255),
url лучше проиндексировать через UNIQUE, мы же по нему находим продукты

2020-04-07 07:10 UTC, zhanymkanov commented on code/repositories/details.py
> +    def init_details(self):
давай абстрагируем эти классы и унаследуем от какого-нибудь BaseRepository, а методы init_details, init_categories объединим в create_table, этот метод по факту же этим и занимается

2020-04-07 07:10 UTC, zhanymkanov commented on code/repositories/details.py
> +    def init_details(self):
По-хорошему вообще будет назвать этот package - models, а эти репозитории сделать моделями соответственно. Сразу с create_table, insert_data и всем остальным. Щас форкну твою ветку, поменяю некоторые абстракции

2020-04-14 09:02 UTC, closed without merging